#!/usr/bin/env bash
set -x
set -eo pipefail  # -u and mamba don't play well: ADDR2LINE: unbound variable

# First system

vi_dir="/usr/local/share/jupyterlab/versions-installed"
mkdir -p ${vi_dir}
cd ${vi_dir}
dpkg -l > "system-dpkgs"
python -m pip list > "system-python"

# Now JupyterLab python

source /usr/local/share/jupyterlab/venv/bin/activate
python -m uv pip list > "jupyterlab-python"
(jupyter labextension list 2>&1) > "lab-extensions"
deactivate

# Now the SPHEREx stack
vi_dir="/opt/spherex/versions-installed"
source /opt/spherex/runtime/loadspherex
mkdir -p ${vi_dir}
cd ${vi_dir}
mamba env export > conda-stack.yaml

