#!/usr/bin/env bash

# This is for Fritz, and my nefarious plan to make the "te" in "Jupyter" TECO.
# We switched from TECOC to Paul Koning's Python implementation because it
#  simplifies installation a bit.  I doubt anyone is going to complain.

src=/usr/local/share/git
mkdir -p ${src}
cd ${src}
git clone https://github.com/pkoning2/pyteco.git
install -m 0755 pyteco/teco.py /usr/local/bin/teco

# The default terminal colors look bad in light mode.
git clone https://github.com/seebi/dircolors-solarized.git
cp dircolors-solarized/dircolors* /etc
