#!/usr/bin/env bash
set -x
set -eo pipefail

# Install Conda
tgt="/opt/spherex"
platform="$(uname -s)"
arch="$(uname -m)"
url="https://github.com/conda-forge/miniforge/releases/latest/download"
fn="Miniforge3-${platform}-${arch}.sh"
url="$url/${fn}"

curl -LO "${url}"

spherex_path="/opt/spherex"
bash ./${fn} -u -b -p $tgt
PATH=$PATH:$spherex_path/bin
export PATH

conda init

conda update -y conda
conda env create -n spx-pipe-base \
      -f ./spherex-pipelines-base-$(arch).yml

# The closed parts of SPHEREx installation should go here.

